# Basics of R
------------------------

## Intro to R

#### Arithmatic operations

In [6]:
(5*2)/(3 - 7)
print(10+5)

[1] -2.5

[1] 15


#### Variables

In [5]:
countOfApples <- 10
countOfOranges <- 20
countOfFruits <- countOfApples + countOfOranges
countOfFruits
print(countOfFruits)

[1] 30

[1] 30


#### Basic data types

In [3]:
## numeric
a <- 10.5
b <- 10

class(a)  # datatype
class(b)

[1] "numeric"

[1] "numeric"

In [7]:
## character
a <- "Sairam"
class(a)

[1] "character"

In [10]:
## boolean/logical
a <- TRUE
class(a)
print(!a)

[1] "logical"

[1] FALSE


#### R Vectors and objects 

In [56]:
## creating a numerical Vector
x <- c(1,2,3,5)  #combine operator

x[1:2]   # subvector

class(x) 
str(x)

x[1]   #first index is 1

y <- x*2
y

[1] 1 2

[1] "numeric"

 num [1:4] 1 2 3 5


[1] 1

[1]  2  4  6 10

In [57]:
-2:3

x <- 5:10
x

y <- x/2
y

[1] -2 -1  0  1  2  3

[1]  5  6  7  8  9 10

[1] 2.5 3.0 3.5 4.0 4.5 5.0

In [37]:
## mean and standard deviation
mean(x)
sd(x)

[1] 2.75

[1] 1.707825

In [53]:
## help system
?mean
help("sum")

In [63]:
## Character vector
names <- c("Sai","Ram","Sai","Shyam")

names
str(names)   # stringify objects
length(names)    # length of vectors

[1] "Sai"   "Ram"   "Sai"   "Shyam"

 chr [1:4] "Sai" "Ram" "Sai" "Shyam"


[1] 4

#### Matrix

In [94]:

M1 <- matrix(9:1,3,3)  ##integer values 

M1
dim(M1)  # dimension
M1[2,2]  # indexing

M1[-1,-2] # submatrix by dropping row and column

M1[-1,2] # submatrix by dropping row and indexing column

M2 <- matrix(c(1,2,3,4),2,2)  ##double(dbl) values
M2


[,1] [,2] [,3]
[1,] 9    6    3   
[2,] 8    5    2   
[3,] 7    4    1

[1] 3 3

[1] 5

[,1] [,2]
[1,] 8    2   
[2,] 7    1

[1] 5 4

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [90]:
## Sequence
seq(5:8)

[1] 1 2 3 4

#### List
A special type of vector containing elements of different classes.

In [98]:

listA <- list(1:3, 3:1, c(46,46,11,3,8))
listA

listA[[2]]

x9 <- list(1,"p", TRUE, 2+4i)
x9

[[1]]
[1] 1 2 3

[[2]]
[1] 3 2 1

[[3]]
[1] 46 46 11  3  8

[1] 3 2 1

[[1]]
[1] 1

[[2]]
[1] "p"

[[3]]
[1] TRUE

[[4]]
[1] 2+4i

#### Factor
Represents categorical data. Can be ordered or unordered

In [105]:

status <- c("low", "high", "medium", "high", "low")

factor(status,ordered=TRUE, levels=c("low","medium","high")) # ordinal categories

factor(status) # nominal categories

[1] low    high   medium high   low   
Levels: low < medium < high

[1] low    high   medium high   low   
Levels: high low medium

#### Data Frames 
Used to store tabular data. Can contain di???erent classes

In [108]:

dframe <- data.frame(c(1,2,3), c("Ram","Sai","Krishna"), c(2.4,23.5,6.8))
dframe

dframe <- data.frame(SLNo=c(1,2,3), Name=c("Ram","Sai","Krishna"), Val=c(2.4,23.5,6.8))
dframe

c.1..2..3. c..Ram....Sai....Krishna.. c.2.4..23.5..6.8.
1 1          Ram                         2.4             
2 2          Sai                        23.5             
3 3          Krishna                     6.8

SLNo Name    Val 
1 1    Ram      2.4
2 2    Sai     23.5
3 3    Krishna  6.8

In [114]:
dframe[1:2,1:3]

dframe[,2:3]

dframe[,1]*3

SLNo Name Val 
1 1    Ram   2.4
2 2    Sai  23.5

Name    Val 
1 Ram      2.4
2 Sai     23.5
3 Krishna  6.8

[1] 3 6 9

In [115]:
dframe$Name  #Accessing column of dataframe
nrow(dframe) # no. of rows in the data
ncol(dframe) # no. of cols in the data
names(dframe) # col names of data

[1] "Ram"     "Sai"     "Krishna"

[1] 3

[1] 3

[1] "SLNo" "Name" "Val"

In [117]:
## read/write to file
write.csv(dframe, file="temp.csv")
read.csv("temp.csv")

write.csv(dframe, file="temp.csv", row.names = FALSE)
read.csv("temp.csv")


X SLNo Name    Val 
1 1 1    Ram      2.4
2 2 2    Sai     23.5
3 3 3    Krishna  6.8

SLNo Name    Val 
1 1    Ram      2.4
2 2    Sai     23.5
3 3    Krishna  6.8

## R Variables

* A valid variable name consists of letters, numbers, the dot, underline characters
* A valid variable name starts with a letter with a dot not followed by a number 
* R reserved words:  
    *if,else, repeat, while, function, for, in, next, break*   
    *TRUE, FALSE, NULL, Inf, NaN, NA, NA_integer_, NA_real_ ,NA_complex_, NA_character_*

In [159]:
## Data Types 
## class() - kind of objects(high-level); typeof() - kind of object's data type(low-level)

x <- 62
class(x)
typeof(x)
x

x <- c(2,25,"gd")
class(x)
typeof(x)
x

[1] "numeric"

[1] "double"

[1] 62

[1] "character"

[1] "character"

[1] "2"  "25" "gd"

In [160]:
## Assignment

semester.marks1 = c(70,80,90,FALSE,TRUE)
semester.marks1

semester.marks2 <- c(TRUE, FALSE)
print(semester.marks2)

[1] 70 80 90  0  1

[1]  TRUE FALSE


'<-' declares variables in user workspace  
'=' when used to set arguments in function call, it is declared in scope of function

In [161]:
## print with strings concat
cat("1st var is", semester.marks1, "\n")

1st var is 70 80 90 0 1 


In [162]:
## vector
empid = vector(length=2) #we need to declare before using empid[i]
empid

empid[1] <- 70
empid[2] <- 51
empid
str(empid)

[1] FALSE FALSE

[1] 70 51

 num [1:2] 70 51


In [163]:
## Variables in memory

# Display all the variables in the current environment
ls() 

# remove all the variables in the current environment
rm(list = ls())
print(ls())

[1] "empid"           "semester.marks1" "semester.marks2" "x"

character(0)


## Operators  


In [4]:
x=4
y=2

x+y  # addition
x-y  # subtraction
x*y  # multiplication
x/y  # division
x^y  # Exponentiation
x%%y # Modular arithmatic
x%/%y # Integer division
x==y  # Equality test
x<=y  # Less than test
x>=y  # Greater than test
x&&y  # Boolean AND for scalars
x||y  # Boolean OR
x&y   # Boolean AND for vectors
x|y   # Boolean OR for vectors
!x    # Boolean negation


[1] 6

[1] 2

[1] 8

[1] 2

[1] 16

[1] 0

[1] 2

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

In [13]:
a=c(TRUE,FALSE,0,6)
b=c(FALSE,TRUE,FALSE,TRUE)

print(!b)

print(a[1]&b[1])
print(a&b)   # element wise operator

print(a[1]|b[1])
print(a|b)   # element wise operator

print(a&&a)
print(a&&b)


[1]  TRUE FALSE  TRUE FALSE
[1] FALSE
[1] FALSE FALSE FALSE  TRUE
[1] TRUE
[1]  TRUE  TRUE FALSE  TRUE
[1] TRUE
[1] FALSE


In [21]:
x>5
isTRUE(x<5)

[1] FALSE

[1] TRUE

[1] TRUE

###### Missing Data

In [25]:
## NA -not available
x=NA
is.na(x)

print(class(NA))
print(typeof(NA))
print(str(NA))


[1] TRUE

[1] "logical"
[1] "logical"
 logi NA
NULL


In [29]:
x <- c(21,22,NA,24)
x

is.na(x)
mean(x)
mean(x,na.rm=TRUE)


[1] 21 22 NA 24

[1] FALSE FALSE  TRUE FALSE

[1] NA

[1] 22.33333

## Control Structures

In [36]:
## if else
test=4
if (test == 4){
    x=1
}else{
    x=3
}
print(x)

[1] 1


In [37]:
## switch
switch(2, "a","b","c")   # switch (expression, list) 

[1] "b"

In [58]:
## for loop

x <- c(5,12,13)
for (n in x){
    print(n^2)
}
print('')

for(i in 1:5){
    print(i^2)
}

[1] 25
[1] 144
[1] 169
[1] ""
[1] 1
[1] 4
[1] 9
[1] 16
[1] 25


In [1]:
## while loop

j = 1
while (j < 5)
{
  print(j^2)
  j = j +2 
}

[1] 1
[1] 9


In [3]:
## repeat loop

m=1
repeat{
    print(m^2)
    m=m+2
    if(m>10){
        break
    }
}

[1] 1
[1] 9
[1] 25
[1] 49
[1] 81
